In [1]:
import csv
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
import tensorflow.contrib.slim as slim

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of num

In [25]:
with open('process/process_file_0.5.csv') as csv_file:
    reader = csv.reader(csv_file)
    data = list(reader)
    
    data = np.array(data)

In [26]:
data[:,0]

array(['TIF', 'CMG', 'DIS', ..., 'V', 'WMT', 'XOM'], dtype='<U20')

In [34]:
label_encoder = preprocessing.LabelEncoder()
one_hot_encoder = preprocessing.OneHotEncoder()
data[:, 0] = label_encoder.fit_transform(data[:, 0])
data = data.astype(float)

In [28]:
data[:,0]

array([386.,  86., 115., ..., 409., 429., 437.])

In [29]:
data

array([[3.86000000e+02, 3.70000000e+01, 0.00000000e+00, 0.00000000e+00,
        7.82699966e+01, 7.82799988e+01],
       [8.60000000e+01, 3.80000000e+01, 4.93900000e-01, 4.01647526e-01,
        4.00500000e+02, 4.02940002e+02],
       [1.15000000e+02, 3.80000000e+01, 2.96000000e-01, 2.19122958e-01,
        1.09559998e+02, 1.09000000e+02],
       ...,
       [4.09000000e+02, 4.90000000e+01, 5.42300000e-01, 4.56404293e-01,
        2.12520004e+02, 2.13309998e+02],
       [4.29000000e+02, 4.90000000e+01, 2.26300000e-01, 1.64280075e-01,
        1.19500000e+02, 1.17680000e+02],
       [4.37000000e+02, 4.90000000e+01, 4.01900000e-01, 3.10354173e-01,
        6.01100006e+01, 6.03400002e+01]])

In [30]:
one_hot_encoder.fit_transform(data[:, 0:2]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
processed_data = one_hot_encoder.fit_transform(data[:, 0:2]).toarray()
processed_data = np.append(processed_data, data[:, 2:6], 1)

In [37]:
one_hot_encoder.fit_transform(np.array([[2,3], [4,5]])).toarray()

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [ ]:
one