In [1]:
import csv
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import numpy as np
import tensorflow.contrib.slim as slim

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of num

In [38]:
with open('process/process_file_0.5.csv') as csv_file:
    reader = csv.reader(csv_file)
    data = list(reader)
    
    data = np.array(data)

In [26]:
data[:,0]

array(['TIF', 'CMG', 'DIS', ..., 'V', 'WMT', 'XOM'], dtype='<U20')

In [34]:
label_encoder = preprocessing.LabelEncoder()
one_hot_encoder = preprocessing.OneHotEncoder()
data[:, 0] = label_encoder.fit_transform(data[:, 0])
data = data.astype(float)

In [28]:
data[:,0]

array([386.,  86., 115., ..., 409., 429., 437.])

In [29]:
data

array([[3.86000000e+02, 3.70000000e+01, 0.00000000e+00, 0.00000000e+00,
        7.82699966e+01, 7.82799988e+01],
       [8.60000000e+01, 3.80000000e+01, 4.93900000e-01, 4.01647526e-01,
        4.00500000e+02, 4.02940002e+02],
       [1.15000000e+02, 3.80000000e+01, 2.96000000e-01, 2.19122958e-01,
        1.09559998e+02, 1.09000000e+02],
       ...,
       [4.09000000e+02, 4.90000000e+01, 5.42300000e-01, 4.56404293e-01,
        2.12520004e+02, 2.13309998e+02],
       [4.29000000e+02, 4.90000000e+01, 2.26300000e-01, 1.64280075e-01,
        1.19500000e+02, 1.17680000e+02],
       [4.37000000e+02, 4.90000000e+01, 4.01900000e-01, 3.10354173e-01,
        6.01100006e+01, 6.03400002e+01]])

In [30]:
one_hot_encoder.fit_transform(data[:, 0:2]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
one_hot_encoder = preprocessing.OneHotEncoder()
processed_data = one_hot_encoder.fit_transform(data[:, 0:2]).toarray()
processed_data = np.append(processed_data, data[:, 2:6], 1)

In [37]:
one_hot_encoder.fit_transform(np.array([[2,3], [4,5]])).toarray()

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [ ]:
one

In [ ]:
from tensorflow.python.client import device_lib
device_lib.list_local_devices()

C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passi

In [3]:
import csv
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

import tensorflow as tf
import tensorflow.contrib.slim as slim


def getData():
    with open('process/process_file_3.csv') as csv_file:
        reader = csv.reader(csv_file)
        data = list(reader)

    return data


def preprocessData(data):
    # check different file
    label_encoder = preprocessing.LabelEncoder()
    one_hot_encoder = preprocessing.OneHotEncoder()

    processed_data = one_hot_encoder.fit_transform(data[:, 0:2]).toarray()
    processed_data = np.append(processed_data, data[:, 2:6], 1)

    processed_data = preprocessing.normalize(processed_data)
    np.random.shuffle(processed_data)

    return processed_data


def learn(data):
    data = preprocessData(data)
    num_params = data.shape[1] - 1

    X = data[:, 0:num_params]
    Y = data[:, num_params].reshape(-1, 1)

    # Split the data into training and testing sets (70/30)
    train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size=0.30)
    train_opening_price = train_X[:, num_params - 1].reshape(-1, 1)
    test_opening_price = test_X[:, num_params - 1].reshape(-1, 1)

    # Get the initial stock prices for computing the relative cost
    stock_data = tf.placeholder(tf.float32, [None, num_params])
    opening_price = tf.placeholder(tf.float32, [None, 1])
    stock_price = tf.placeholder(tf.float32, [None, 1])

    # Number of neurons in the hidden layer
    n_hidden_1 = 3
    n_hidden_2 = 3

    weights = {
        'out': tf.Variable(tf.random_normal([n_hidden_2, 1]))
    }
    biases = {
        'out': tf.Variable(tf.random_normal([1]))
    }

    # Implement dropout to reduce overfitting
    keep_prob_input = tf.placeholder(tf.float32)
    keep_prob_hidden = tf.placeholder(tf.float32)

    # Hidden layers
    input_dropout = tf.nn.dropout(stock_data, keep_prob_input)
    layer_1 = slim.fully_connected(input_dropout, n_hidden_1, biases_initializer=None, activation_fn=tf.nn.relu)
    layer_1_dropout = tf.nn.dropout(layer_1, keep_prob_hidden)
    layer_2 = slim.fully_connected(input_dropout, n_hidden_1, biases_initializer=None, activation_fn=tf.nn.relu)
    layer_2_dropout = tf.nn.dropout(layer_2, keep_prob_hidden)
    output_layer = tf.add(tf.matmul(layer_2_dropout, weights['out']), biases['out'])

    learning_rate = 1e-4
    cost_function = tf.reduce_mean(tf.pow(tf.div(tf.subtract(stock_price, output_layer), opening_price), 2))
    optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost_function)

    last_cost = 0
    tolerance = 1e-6
    epochs = 1
    max_epochs = 1e6

    config  = tf.ConfigProto(log_device_placement = True)
    sess = tf.Session(config=config)
    with sess:
        init = tf.global_variables_initializer()
        sess.run(init)

        while True:
            sess.run(optimizer,
                     feed_dict={stock_data: train_X, opening_price: train_opening_price, stock_price: train_Y,
                                keep_prob_input: 0.8, keep_prob_hidden: 0.5})

            if epochs % 100 == 0:
                cost = sess.run(cost_function, feed_dict={stock_data: train_X, opening_price: train_opening_price,
                                                          stock_price: train_Y, keep_prob_input: 0.8,
                                                          keep_prob_hidden: 0.5})
                print("Epoch: %d: Error: %f" % (epochs, cost))

                if abs(cost - last_cost) <= tolerance or epochs > max_epochs:
                    print("Converged.")
                    break
                last_cost = cost

            epochs += 1

        print("Test error: ", sess.run(cost_function, feed_dict={stock_data: test_X, opening_price: test_opening_price,
                                                                 stock_price: test_Y, keep_prob_input: 1.0,
                                                                 keep_prob_hidden: 1.0}))
        test_results = sess.run(output_layer, feed_dict={stock_data: test_X, stock_price: test_Y, keep_prob_input: 1.0,
                                                         keep_prob_hidden: 1.0})

    avg_perc_error = 0
    max_perc_error = 0
    mei = 0
    for i in range(len(test_Y)):
        actual_change = abs(test_Y[i][0] - test_X[i][num_params - 1]) / test_X[i][num_params - 1]
        predicted_change = abs(test_results[i][0] - test_X[i][num_params - 1]) / test_X[i][num_params - 1]
        delta = abs(actual_change - predicted_change)
        avg_perc_error = avg_perc_error + delta
        if delta > max_perc_error:
            max_perc_error = delta
            mei = i

    avg_perc_error = (avg_perc_error * 100) / len(test_Y)
    max_perc_error *= 100
    print("Maximum percentage error: %f\nAverage percentage error: %f\n" % (max_perc_error, avg_perc_error))


def main():
    data = np.array(getData())
    learn(data)


main()


Device mapping:
/job:localhost/replica:0/task:0/device:GPU:0 -> device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1

Epoch: 100: Error: 2.054140
Epoch: 200: Error: 1.997147
Epoch: 300: Error: 1.941942
Epoch: 400: Error: 1.885184
Epoch: 500: Error: 1.759476
Epoch: 600: Error: 1.638179
Epoch: 700: Error: 1.540237
Epoch: 800: Error: 1.451092
Epoch: 900: Error: 1.367979
Epoch: 1000: Error: 1.295520
Epoch: 1100: Error: 1.226288


KeyboardInterrupt: 